### PR TITLE
Always close regardless of the contents of the PR

### PR DESCRIPTION
**Pull request by segiddins**
\c @orta 

We also need to come up with a new message -- it's currently

> We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/ #12199 (this was closed automatically, if your pull request should not be closed based on that issue, please reopen it)

### CODE REVIEW

**Comment by segiddins** [comment]
I'd advocate something like

> The CocoaPods specs repository can only be updated via [CocoaPods trunk](http://blog.cocoapods.org/CocoaPods-Trunk/). To push a new version, use `pod trunk push`. To delete a version of an existing pod, use `pod trunk delete`. To mark all existing versions of a pod as deprecated, use `pod trunk deprecate`. (To deprecate or delete, you need to be running CocoaPods 1.0.) If you don't have permission on trunk to update a pod, please [file a claim](http://blog.cocoapods.org/Claim-Your-Pods/). For more information, please see #12199. (Note that this pull request was closed automatically, as this repo no longer accepts any pull requests).

**Comment by orta** [comment]
What about?

> Back in early 2014 we [launched CocoaPods Trunk](http://blog.cocoapods.org/CocoaPods-Trunk/). Trunk is the only way that you can submit pods to CocoaPods, we do not accept pull requests to the CocoaPods Specs repo, and so this is being auto-closed. Please see #12199 for more info, or the guide on [getting started with trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk.html).
> - To push a new version to trunk, you can use `pod trunk push`
> - You cannot amend an existing pod, however you can delete and deprecate a pod. You need to be using CocoaPods 1.0 to have access to `pod trunk delete` and `pod trunk deprecate`. People may be relying on your pod version, so use these with caution.
> - If you don't have permission to update a pod that you own, please [file a claim](http://blog.cocoapods.org/Claim-Your-Pods/) on trunk.

**Comment by segiddins** [comment]
@k0nserv could you please review this?

**Comment by k0nserv** [comment]
Looks good, might wanna include a link to https://guides.cocoapods.org/making/getting-setup-with-trunk.html somewhere. My only other nitpic is that it might be slightly better to make the file reading slightly more lazy.

**Comment by segiddins** [comment]
@k0nserv lazy in what sense? Currently it's re-read every request

**Comment by k0nserv** [comment]
Essentially not re-read every request, maybe read only once into memory on start

**Comment by k0nserv** [comment]
But again it's nitpic territory. PR is 🆗

**Comment by segiddins** [comment]
🚢

**Comment by orta** [comment]
cool, updated my comment too ^

**Pull request merged**
